### ISSUE TITLE
Please add Categories= entry to the desktop file

### ISSUE THREAD

**Issue by probonopd** [ra-gg/Delir#202]
Please add a `Categories=` entry to the desktop file.

References:
* https://github.com/AppImage/appimage.github.io/pull/1197/files
* https://github.com/AppImage/appimage.github.io/issues/2

**Comment by ra-gg** [comment]
Thanks I'll trying this.

**Comment by ra-gg** [comment]
Maybe fix it. Please check out https://github.com/ra-gg/Delir/releases/tag/v0.6.0

**Comment by probonopd** [comment]
Thank you.
